### ISSUE TITLE
EME Call and Event Logger breaks PayPal convert currency

### ISSUE THREAD

**Issue by matthuisman** [shaka-project/eme_logger#45] opened 2022-05-14 02:09 UTC
with this extension enabled, clicking on the 3 dots next to a currency in Paypal won't open the convert current pop-up

https://www.paypal.com/myaccount/money/
![image](https://user-images.githubusercontent.com/6225961/168406886-1437d83e-5e1d-4ce7-9b85-b58ec56a3e8a.png)

With this extension enabled - the above pop-up menu won't show. Clicking the dots does nothing.

Chrome console:
Refused to load the script 'https://www.googleadservices.com/pagead/conversion_async.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' 'unsafe-inline' https://*.paypal.com https://*.paypalobjects.com". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

However this error is unrelated as it shows with the extension enabled or not.
But only when extension disabled does Paypal function correctly

**Comment by matthuisman** [comment] 2022-05-14 04:07
Maybe this is due to https://github.com/shaka-project/eme_logger/issues/44

**Comment by joeyparrish** [comment] 2022-05-14 14:55
Yes, I think so.  If you want to send a PR for this / #44, I would be happy to review it.

**Comment by joeyparrish** [comment] 2022-05-24 19:20
Duplicate of #44

**Closed by joeyparrish** 2022-05-24 19:20 UTC
Labels: type: bug, status: duplicate, priority: P1
